### ISSUE TITLE
Reminder shows up even if I have already tracked that day.

### ISSUE THREAD

**Issue by johannesschweig** [mrzmyr/pixy-mood-tracker-app#13]
I set up a reminder for the evening in the settings, but it shows up even if I have already tracked that day.

I would expect it to only show up if I have not already tracked that day.

Phone: OnePlus Nord
Android: 12

**Comment by mrzmyr** [comment]
Hi @johannesschweig, indeed this is the expected behavior atm. I think it should be possible to archive this by utilizing `setNotificationHandler` and [using a background task](https://docs.expo.dev/versions/latest/sdk/notifications/#registertaskasynctaskname-string-void).

Just put it on the [feedback panel](https://pixy.hellonext.co/) with your name. Let's see how the users vote on it.

Thanks for the feedback ✨
