### ISSUE TITLE
Complete offline mode

### ISSUE THREAD

**Issue by hannesknutsson** [mrzmyr/pixy-mood-tracker-app#183]
I have found your app because I wanted a mood tracker with cool statistics that is open source and keeps all data on my own device.

I am running [iodéOS](https://iode.tech/en/) and have noticed that even though I've read that Pixy [data is stored on the device only](https://alternativeto.net/software/pixy-mood-tracker/about/), my instance of the app still tried to make requests to various domains.

These requests may not have contained much private "mood data", but since the information this app handles is very personal  this worries me a bit.

I have not read the code, but as I understand it; If all data is local, the app should never need to make requests to external resources.

Is it possible to get a toggle that completely shuts off all outwards facing communication?
What, if anything, would I miss out on if I enabled this toggle?

**Comment by mrzmyr** [comment]
Hi @hannesknutsson, I'm delighted that someone has finally brought up this topic. The data you provide is exclusively stored on your device, which means it is not synchronized with any cloud-based system. Nonetheless, as indicated in the privacy section of the settings, behavioral data is collected using PostHog. It's important to note that Pixy values user privacy, and you have the option to disable this feature in the settings. Although I must admit, I appreciate it when users share their data because it is fully anonymized and assists me in gaining insights on how to enhance Pixy.

Another feature that sends requests is the update functionality of [Expo](expo.dev), which takes advantage of React Native's capability to update the app in the background without relying on the App Store. However, it's worth noting that removing web access for the app at the operating system level will prevent this update process from occurring.

Hope this answers your questions.

**Comment by hannesknutsson** [comment]
Thank you for you reply.

If I completely block the apps network access, will I forever be stuck on the version of the app I am right now, or will the app _eventually_ be updated through the store as well? I don't mind waiting longer for updates, but it would be cool to get them eventually.

Personally I will not be enabling network access for any app with this type of sensitive information, so I won't be much help with behavioral data. But if you have anything similar to [this](https://www.buymeacoffee.com/) I wouldn't mind making a donation to support your privacy conscious open source mood tracker app. I would love to support the development of this in some way.

Thanks again.
